collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5406278818845749
color:
  saturation: 0.4396988139487803
  brandStrength: 0.3695098964963108
  lightness: 0.3569863166194409
  brandColors:
    - '#000000'
    - '#6E8AA2'
    - '#88ADC0'
    - '#2B3244'
    - '#E1F3F5'
  rhythmicContrast: 0.8399129677563906
layout_spectrum: 0.0393013774883002
name: roger
