author:
  name: Roger Cavanagh
  email: roger.cavanagh@mac.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5194235
color:
  saturation: 0
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#CBC9CE'
    - '#F4F3FB'
    - '#756F57'
    - '#A59F93'
    - '#572126'
  lightness: 1
layout_spectrum: 0.6332209
name: roger
