collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5406278818845749
color:
  saturation: 0.1277985
  brandStrength: 0.3695098964963108
  lightness: 1
  brandColors:
    - '#000000'
    - '#6E8AA2'
    - '#88ADC0'
    - '#2B3244'
    - '#E1F3F5'
  rhythmicContrast: 1
layout_spectrum: 0.0393013774883002
name: roger
