author:
  name: Roger Cavanagh
  email: roger.cavanagh@mac.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#D8D8DA'
    - '#C0B1AA'
    - '#B19884'
    - '#AE816A'
    - '#8C7465'
  rhythmicContrast: 1
typography_spectrum: 0.4376054
layout_spectrum: 0.242833
name: roger
