collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5149254
color:
  saturation: 0.1277985
  brandStrength: 0.4943609
  lightness: 1
  brandColors:
    - '#000000'
    - '#6E8AA2'
    - '#88ADC0'
    - '#2B3244'
    - '#E1F3F5'
  rhythmicContrast: 1
layout_spectrum: 0.8754664
name: roger
author:
  name: Roger Cavanagh
  email: roger.cavanagh@mac.com
